paths:
  input: dados/originais/SEDEC
  Year_start: 2015
  Year_end: 2026
  output: dados/originais/SEDEC


excel:
  nome_saida: tabelasedec.xlsx

# database:
#   tabela_fato: fato_despesas
#   tabelas_dimensoes:
#     tempo: dim_tempo
#     entidade: dim_entidade
#     fornecedor: dim_fornecedor
#     categoria: dim_categoria

pipeline:
  modo_carga: append   # append | replace | upsert
  chunk_size: 1000     # performance em grandes volumes

colunas:
  data: data
  entidade: entidade
  fornecedor: fornecedor
  categoria: categoria
  valor: valor
  descricao: descricao

Processamento:
  formatos_aceitos:
    - ".html"
    - ".xls"
    - ".xlsx"
    - ".csv"

  deletar_apos_processamento: False

  remover_duplicados: true

  coluna_chave: "numero_contrato" #usardo para duplicação