paths:
  input: dados/processadas/tabela_unificada.xlsx
  output: dados/processadas

  years:
    start : 2015
    end : 2026

excel:
  nome_saida: tabela_processada.xlsx

CSV:
  nome_saida: diarias_final.csv

pipeline:
  modo_carga: append   # append | replace | upsert
  chunk_size: 1000     # performance em grandes volumes



Processamento:
  formatos_aceitos:
    - ".html"
    - ".xls"
    - ".xlsx"
    - ".csv"

  deletar_apos_processamento: False

  remover_duplicados: true
