paths:
  input: dados/processadas/tabela_fundes_cedec_pront.xlsx
  output: dados/processadas


excel:
  nome_saida: tabela_fundes_cedec_pront.xlsx



pipeline:
  modo_carga: append   # append | replace | upsert
  chunk_size: 1000     # performance em grandes volumes



Processamento:
  formatos_aceitos:
    - ".html"
    - ".xls"
    - ".xlsx"
    - ".csv"

  deletar_apos_processamento: False

  remover_duplicados: true
